#!/bin/bash

set -euf -o pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE ROLE jmdictdb PASSWORD 'jmdictdb' NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN;
    CREATE ROLE jmdictdbv PASSWORD 'jmdictdbv' NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN;
EOSQL
